GestionProject/Controllers/ChatController.cs
using GestionProject.Data;
using GestionProject.Models;
using GestionProject.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace GestionProject.Controllers
{
    public class ChatController : Controller

    {

        private readonly AppDbContext _appDbContext;

        public ChatController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }

        public IActionResult Index(IFormFile files)

     
           
        {
            if (files != null)
            {
                if (files.Length > 0)
                {
                    //Getting FileName
                    var fileName = Path.GetFileName(files.FileName);
                    //Getting file Extension
                    var fileExtension = Path.GetExtension(fileName);
                    // concatenating  FileName + FileExtension
                    var newFileName = String.Concat(Convert.ToString(Guid.NewGuid()), fileExtension);

                    var chat = new Chat()
                   

                    {
                        DocumentId = 0,
                        Name = newFileName,
                        FileType = fileExtension,
                        when = DateTime.Now
                    };

                    using (var target = new MemoryStream())
                    {
                        files.CopyTo(target);
                       chat.DataFiles = target.ToArray();
                    }

                    _appDbContext.Chats.Add(chat);
                    _appDbContext.SaveChanges();

                }
            }
            return View();
        }
    }
}

GestionProject/Controllers/TasksController.cs
using GestionProject.Data;
using GestionProject.Models;
using GestionProject.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace GestionProject.Controllers
{
    public class TasksController : Controller

    {

        private readonly AppDbContext _appDbContext;

        public TasksController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }

        public IActionResult Index()

        {

            var model = new List<TaskViewModel>();
            var tasks = _appDbContext.Tasks.Include(x => x.ProjectTeamMembers).ToList();

            foreach (var task  in tasks)
			{
                model.Add(new TaskViewModel{

                            Teams = task.Group,
                            NameTask = task.NameTask,
                            DueDate = task.DueDate,

                        });
			}
            return View(model);


            List<TeamMemberselect> TeamMembers = new List<TeamMemberselect>
            {

                new  TeamMemberselect { TeamMemberId=1, Group= "API" },
                new  TeamMemberselect{ TeamMemberId=2, Group= "UI" },
                 new  TeamMemberselect { TeamMemberId=3, Group= "BIG DATA" },



            };

            List<TeamMemberselect> SelectedTeamMembers = new List<TeamMemberselect>
            {
                 new   TeamMemberselect{ TeamMemberId=1, Group= "API" },
                new   TeamMemberselect{ TeamMemberId=2, Group= "UI" },

            };
            var DetailsModel = new TaskViewModel();
            DetailsModel.TeamMemberId = SelectedTeamMembers.Select(x => x.TeamMemberId).ToList();
            DetailsModel.TeamMemberlist = TeamMembers.ToList().ConvertAll<SelectListItem>(k =>
            {
                return new SelectListItem()
                {
                    Value = k.TeamMemberId.ToString(),
                    Text = k.Group
                };
               
            });
               return View(DetailsModel);

        }

          
        

        [HttpGet]
        public IActionResult Create()
        {

             Tasks task = new Tasks();
          
                return PartialView("_Add", task);
             }
        [HttpPost]
        public IActionResult Create(Tasks task)
        {
            _appDbContext.Tasks.Add(task);
            return PartialView("_Add", task);
        }

        public IActionResult Delete([FromQuery]int? id)
        {

            var task = _appDbContext.Tasks.Find(id);
            if (task == null)
            {

                return View();
            }


            _appDbContext.Tasks.Remove(task);
            _appDbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}



     //   [HttpPost]
     //   public IActionResult Update(int? id)
      //  {

          
         //   if (id==null || id ==0)
		//	{
            //    return NotFound();
		//	}
          //  var task= _appDbContext.Tasks.Find(id);
          //  if (task == null)
		//	{
            //    return NotFound();
		//	}

          //  return View(task);

   

GestionProject/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace GestionProject.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Index()
    {
        return View();
    }
}
}

GestionProject/Views/Shared/_DashboardLayout.cshtml
@{ Layout = "_Layout"; }
<div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="border-right" id="sidebar-wrapper">
        <div class="sidebar-heading">Management Project</div>
        <div class="list-group list-group-flush">
            <!-- /#dashboard -->
            <a  asp-action="Dashboard" asp-controller="Home" class="list-group-item list-group-item-action"><i class="far fa-chart-bar"></i> Dashboard</a>
            <!-- /clients -->
            <a  data-toggle="collapse" data-target="#menu1" class="list-group-item list-group-item-action collapsed"><i class="fas fa-user"></i> <span class="nav-label"> Clients</span><span class="fa fa-chevron-left float-right"></span></a>
            <ul class="sub-menu collapse1" id="menu1">
                <li><a class="list-group-item list-group-item-action" asp-action="Index" asp-controller="Client"> list Clients</a></li>
                <li><a class="list-group-item list-group-item-action" asp-action="Add" asp-controller="Client"> add Clients</a></li>
            </ul>
            <!-- /#Projects-->
            <a data-toggle="collapse" data-target="#menu2" class="list-group-item list-group-item-action collapsed"><i class="fas fa-briefcase"></i> <span class="nav-label">Projects</span><span class="fa fa-chevron-left float-right"></span></a>
            <ul class="sub-menu collapse" id="menu2">
                <li><a class="list-group-item list-group-item-action" asp-action="Index" asp-controller="Project"> list Project</a></li>
                <li><a class="list-group-item list-group-item-action" asp-action="Add" asp-controller="Project"> add Projects</a></li>
            </ul>
            <!-- /#tasks-->
            <a data-toggle="collapse" data-target="#menu3" class="list-group-item list-group-item-action collapsed"><i class="fas fa-tasks"></i> <span class="nav-label">Tasks</span><span class="fa fa-chevron-left float-right"></span></a>
            <ul class="sub-menu collapse" id="menu3">
                <li><a class="list-group-item list-group-item-action" asp-action="index" asp-controller="Tasks"> Tasks</a></li>
            </ul>
            <!-- /#chat-->
            <a class="list-group-item list-group-item-action"asp-controller="Chat" asp-action="index"> <i class="far fa-comment"></i> Chat</a>
            <!-- /#settings-->

            <a data-toggle="collapse" data-target="#menu5" class="list-group-item list-group-item-action collapsed"><i class="fas fa-user-cog"></i><span class="nav-label"> Settings</span><span class="fa fa-chevron-left float-right"></span></a>
            <ul class="sub-menu collapse" id="menu5">
                <li><a class="list-group-item list-group-item-action" asp-action="Index" asp-controller="User"> Users</a></li>
                <li><a class="list-group-item list-group-item-action" asp-action="index" asp-controller="TeamMember">Teams</a></li>
            </ul>
        </div>
    </div>
    <!-- /#sidebar-wrapper -->
    <!-- Page Content -->
    <div id="page-content-wrapper">

        <nav class="navbar navbar-expand-lg navbar-light border-bottom">
            <a class="" id="menu-toggle"><i class="fas fa-bars"></i></a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto mt-2 mt-lg-0">


                    <li class="nav-item dropdown">
                        <a class="nav-link"id="navbarDropdown" role="button" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-sign-out-alt"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                            <a class="dropdown-item" >Log out </a>


                        </div>
                    </li>
                </ul>
            </div>
        </nav>
        <!--dashboard-->
        @RenderBody()
    </div>
</div>
@await RenderSectionAsync("Scripts", required: false)
<!-- Menu Show Script -->
<script>
    $("#menu-toggle").click(function (e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });</script>

GestionProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestionProjet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/index.css" />
    <!-- Fontawsome CSS -->
    <link href="~/assets/fonts/fontawesome/css/all.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/assets/css/app.css" rel="stylesheet">


    <link rel="stylesheet" href="~/css/style.css">
</head>
<body>
    @RenderBody()
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>